version: 2.1
orbs:
  python: circleci/python@1.4.0

jobs:
  build:
    docker:
      - image: cimg/python:3.8
      - image: postgres:13.3
        environment:
          POSTGRES_USER: youruser
          POSTGRES_DB: yourtestdb
          POSTGRES_PASSWORD: yourpassword
    steps:
      - checkout
      - run:
          name: Wait for DB
          command: |
            for i in `seq 1 10`;
            do
              nc -z localhost 5432 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for DB && exit 1
      - python/install-packages:
          pkg-manager: pip
          pip-dependency-file: requirements.txt
      - run:
          name: Run tests
          command: |
            pytest --junitxml=junit.xml
      - store_test_results:
          path: junit.xml
      - store_artifacts:
          path: junit.xml
