version: 2.1
orbs:
  python: circleci/python@1.4.0

jobs:
  build:
    docker:
      - image: cimg/python:3.8
      - image: circleci/postgresql:13.3  # Use PostgreSQL docker image
        environment:
          POSTGRES_USER: youruser  # Default user
          POSTGRES_DB: yourtestdb  # Default database
          POSTGRES_PASSWORD: yourpassword  # Password for default user

    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          pip-dependency-file: requirements.txt

      - run:
          name: Wait for DB
          command: |
            for i in `seq 1 10`;
            do
              nc -z localhost 5432 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for DB && exit 1

      - run:
          name: Run tests
          command: |
            pytest --junitxml=junit.xml

      - store_test_results:
          path: junit.xml
      - store_artifacts:
          path: junit.xml

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
