version: 2.1
orbs:
  python: circleci/python@1.4.0  # Update the orb version if necessary

jobs:
  test-python:
    docker:
      - image: cimg/python:3.8  # Use Python 3.8 image
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip  # Make sure this uses pip if you are using a requirements.txt
          pip-dependency-file: requirements.txt  # Specify your dependency file accurately
      - run:
          name: Run tests
          command: |
            pytest --junitxml=junit.xml  # Run pytest and generate a JUnit XML report
      - store_test_results:
          path: junit.xml  # Store the results for CircleCI's test summary
      - store_artifacts:  # Optional: store test artifacts (like logs)
          path: junit.xml

  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Deploy to Production
          command: |
            echo "Deploy steps go here"
            # Add your actual deploy commands here

workflows:
  build-and-test:
    jobs:
      - test-python
      # Uncomment the next lines when the deploy job is ready to be used
      # - deploy:
      #     requires:
      #       - test-python
