version: 2.1
orbs:
  python: circleci/python@1.4.0

jobs:
  build:
    docker:
      - image: cimg/python:3.8
      - image: postgres:13.3
        environment:
          POSTGRES_USER: circleci
          POSTGRES_PASSWORD: pleased
          POSTGRES_DB: capstone_test
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
      - run:
          name: Wait for DB
          command: |
            for i in `seq 1 10`;
            do
              PGPASSWORD=pleased psql -h localhost -U circleci -d capstone_test -c "SELECT 1" && echo "Success" && exit 0
              echo -n "."
              sleep 1
            done
            echo "Failed waiting for DB" && exit 1
      - run:
          name: Run tests
          command: |
            pytest --junitxml=junit.xml
      - store_test_results:
          path: junit.xml
      - store_artifacts:
          path: junit.xml
