version: 2.1
orbs:
  python: circleci/python@1.2.0
  heroku: circleci/heroku@1.2.6
jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.8  # Choose the Python version you need
    environment:
      PIPENV_VERBOSITY: -1
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pipenv
      - run:
          name: Database Setup
          command: |
            # Setup your database here. You might need to customize these commands
            # For example, if you're using Flask-SQLAlchemy
            flask db upgrade
            flask db create
      - run:
          name: Run Tests
          command: |
            # Run your test suite here
            pytest
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: test-results
  deploy:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git:
          app-name: YOUR_HEROKU_APP_NAME

workflows:
  build-deploy:
    jobs:
      - build-and-test
      - deploy:
          requires:
            - build-and-test
          filters:
            branches:
              only: main
